export const GET_WEATHER_REQUEST = "GET_WEATHER_REQUEST";
export const GET_WEATHER_SUCCESS = "GET_WEATHER_SUCCESS";
export const GET_WEATHER_FAILURE = "GET_WEATHER_FAILURE";

export const GET_WEATHER_ALL_REQUEST = "GET_WEATHER_ALL_REQUEST";
export const GET_WEATHER_ALL_SUCCESS = "GET_WEATHER_ALL_SUCCESS";
export const GET_WEATHER_ALL_FAILURE = "GET_WEATHER_ALL_FAILURE";

export const BOOKMARK_REQUEST = "BOOKMARK_REQUEST";
export const BOOKMARK_SUCCESS = "BOOKMARK_SUCCESS";
export const BOOKMARK_FAILURE = "BOOKMARK_FAILURE";

export const SHARE_WEATHER_REQUEST = "SHARE_WEATHER_REQUEST";
export const SHARE_WEATHER_SUCCESS = "SHARE_WEATHER_SUCCESS";
export const SHARE_WEATHER_FAILURE = "SHARE_WEATHER_FAILURE";